import Link from 'next/link'
import './globals.css'
import localFont from 'next/font/local'

const recursive = localFont({
  src: './assets/fonts/Recursive_VF_1.085.woff2',
  display: 'swap',
  weight: '350 1000',
  style: 'oblique 0deg 14deg',
  variable: '--vf-recursive'
})

export const metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const links = [
    { href: '/', label: 'Home' },
    { href: '/docs', label: 'Docs' },
    { href: '/todos', label: 'Todo List' },
  ]

  return (
    <html lang="en">
      <body className={recursive.variable}>
        <header>
          <nav>
            <ul className='flex items-center'>
              { links.map( link => (
                <li key={ link.href }>
                  <Link href={ link.href }>{ link.label }</Link>
                </li>
              )) }
            </ul>
          </nav>
        </header>
        <div>
          { children }
        </div>
      </body>
    </html>
  )
}
